# Generated by Django 4.2.8 on 2023-12-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Тема письма')),
                ('body_message', models.TextField(verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'Пиьсмо',
                'verbose_name_plural': 'Письма',
            },
        ),
    ]
