# Generated by Django 4.2.8 on 2023-12-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_image/', verbose_name='Аватар'),
        ),
    ]
